### ISSUE TITLE
Camera doesn't apply multiple rotation settings

### ISSUE THREAD

**Issue by NotExpectedYet** [NotExpectedYet/OctoFarm#23]
Camera currently only applies the top rotational setting and doesn't apply both.

**Comment by NotExpectedYet** [comment]
Just on views from my tests

**Comment by dburr** [comment]
In my case, "Camera currently only applies the top rotational setting" does not seem to apply. I have my RasPi camera mounted upside down because of cable management issues, and so I have to have both "flip horizontally" and "flip vertically" enabled. However OctoFarm shows the image correctly flipped vertically, but NOT flipped horizontally as it should be (so, in effect, the image appears mirrored.) So in my case it's the SECOND setting (flip vertically) that is being correctly applied, NOT the first (flip horizontally.)
![Screen Shot 2020-04-12 at 2 13 47 PM](https://user-images.githubusercontent.com/1237762/79080085-ec1ed080-7cc7-11ea-85b0-65a185c6f53b.png)
![Screen Shot 2020-04-12 at 2 13 52 PM](https://user-images.githubusercontent.com/1237762/79080087-ed4ffd80-7cc7-11ea-8fcb-a1318b4ff6d7.png)

**Comment by NotExpectedYet** [comment]
The title doesn't say that, I'd edited it... As it says it applies the first, not multiple. Will be fixed in a later release.

**Comment by dburr** [comment]
> The title doesn't say that, I'd edited it... As it says it applies the first, not multiple. Will be fixed in a later release. Just because it's first there doesn't mean it's first in the code as well. I know where the bug is but thanks for the additional info.

OK, thanks for the reply. Looking forward to it -- viewing my (printer's) world horizontally flipped is a bit disorientating ;-)

**Comment by NotExpectedYet** [comment]
No worries :) Yeah can imagine, I got lazy when I was doing the views if I'm honest. I remember thinking, no one will need both aha. Certainly be sorted for the release of 1.1.5 though. I don't have any work arounds at the minute either but I'll see if I can push that to master within the week for you as  a few other people have mentioned it.

**Comment by NotExpectedYet** [comment]
@dburr 1.1.5 is on development currently and fixes that. You can check the changelog to see if you want to change over. Currently there's some stat's missing but everything else is in there.

**Comment by jcassar** [comment]
Hello, does this behavior was resolved? I am running OctoFarm 1.1.13-hotfix and OctoPrint Version 1.6.1 and got the same issues when Flip webcam horizontally and vertically are selected in Webcam & Timelapse panel. Any ideas to have the world horizontally flipped. Thanks!

**Comment by jcassar** [comment]
No worries, restarting octoprint fix that.
