### ISSUE TITLE
[QUESTION] Interested in merging printer map module

### ISSUE THREAD

**Issue by InfoMTB3D** [NotExpectedYet/OctoFarm#256]
I've started working on a printer location map tab based on the latest OctoFarm. This module is going to be suitable for 'big fingers' and tablet-devices (touch devices). And will allow 'mass-printing' by quickly selecting multiple printers and assigning/dragging-dropping a file to mass print on many printers.
Last feature: it will allow mapping certain printers to their physical location based on a naming convention + octoprint port setting (yeah that needs some discussion).

Context: 3D printer company reaching it's scalability limits.

![image](https://user-images.githubusercontent.com/77500910/107036734-5bffc980-67ba-11eb-80fd-43759cc6064a.png)
(Disclaimer: this is just a prototype image and not the final version)

Is there interest into merging this into OctoFarm?
I can provide details on my future plans, if there is interest. Work will continue on this client worker/view.

**Comment by NotExpectedYet** [comment]
I am interested totally, this sounds cool. 

I am trying to think currently how this will work with my current changes working towards 1.2. Initially I have had reservations of taking commits to the main code because the current base is a mess, it's not modular and it's got a lot of my learning errors in it. There's also maintainability, so I'd like to obviously understand the code to keep it up if you decided to no longer, or someone wanted an extra feature I could add myself and you weren't available.  

Do you have a branch I can look at and test out across my testing instances? I am happy to work with you on this totally but all the work on 1.2 will  be going on a private branch for patreons initially because it's about time I gave my supporters something extra. That's whilst it's in development then Private will stay a version or two in front. 

Would you like to open a discussion and we can flesh this out further. Happy for the help, and it sounds like a cool feature.

**Comment by InfoMTB3D** [comment]
No worries, I will PR after I remove our private code. Also, I will consider to join in open-source wise because I have quite some experience I can share with you. I'll shoot you an email for that.

Discussion is made, let's talk!
